# Generated by Django 4.1.7 on 2023-05-06 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossarySentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=5000)),
                ('source_language', models.CharField(max_length=5)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'glossary_sentence',
            },
        ),
        migrations.CreateModel(
            name='GlossaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('source_language', models.CharField(max_length=2)),
                ('grammatical_category', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'glossary_word',
            },
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100)),
                ('deck_template', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_deck',
            },
        ),
        migrations.CreateModel(
            name='TransWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_word', models.CharField(blank=True, max_length=500)),
                ('target_language', models.CharField(max_length=2)),
                ('source_language', models.CharField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.glossaryword')),
            ],
            options={
                'db_table': 'translated_glossary_word',
            },
        ),
        migrations.CreateModel(
            name='TransSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_sentence', models.TextField(blank=True)),
                ('target_language', models.CharField(max_length=5)),
                ('source_language', models.CharField(max_length=5)),
                ('sentence_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.glossarysentence')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'translated_glossary_sentence',
            },
        ),
        migrations.AddField(
            model_name='glossaryword',
            name='deck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userdeck'),
        ),
        migrations.AddField(
            model_name='glossaryword',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glossarysentence',
            name='deck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userdeck'),
        ),
        migrations.AddField(
            model_name='glossarysentence',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
