# Generated by Django 4.1.7 on 2023-05-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transsentence",
            old_name="translated_sentence",
            new_name="sentence_translation",
        ),
        migrations.RenameField(
            model_name="transword",
            old_name="translated_word",
            new_name="word_translation",
        ),
        migrations.AlterField(
            model_name="glossarysentence",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="glossarysentence",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="glossaryword",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="glossaryword",
            name="grammatical_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="glossaryword",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userdeck",
            name="deck_name",
            field=models.CharField(max_length=100, verbose_name="deck"),
        ),
        migrations.AlterField(
            model_name="userdeck",
            name="deck_template",
            field=models.TextField(blank=True, null=True, verbose_name="template"),
        ),
        migrations.AlterModelTable(
            name="glossarysentence",
            table="sentence_glossary",
        ),
        migrations.AlterModelTable(
            name="glossaryword",
            table="word_glossary",
        ),
        migrations.AlterModelTable(
            name="transsentence",
            table="sentence_translations_glossary",
        ),
        migrations.AlterModelTable(
            name="transword",
            table="word_translations_glossary",
        ),
    ]
