# Generated by Django 4.1.7 on 2023-05-18 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0002_rename_translated_sentence_transsentence_sentence_translation_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="glossarysentence",
            old_name="deck_id",
            new_name="deck",
        ),
        migrations.RenameField(
            model_name="glossarysentence",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="glossaryword",
            old_name="deck_id",
            new_name="deck",
        ),
        migrations.RenameField(
            model_name="glossaryword",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="transsentence",
            old_name="sentence_id",
            new_name="sentence",
        ),
        migrations.RenameField(
            model_name="transsentence",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="transword",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="transword",
            old_name="word_id",
            new_name="word",
        ),
        migrations.RenameField(
            model_name="userdeck",
            old_name="user_id",
            new_name="user",
        ),
    ]
