# Generated by Django 4.1.7 on 2023-05-21 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0003_rename_deck_id_glossarysentence_deck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransGlossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.TextField(blank=True, null=True)),
                ("target_language", models.CharField(max_length=50)),
                ("source_language", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "translation",
                "verbose_name_plural": "translations",
                "db_table": "glossary_translations",
            },
        ),
        migrations.CreateModel(
            name="UserGlossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vocabulary", models.CharField(max_length=5000)),
                ("source_language", models.CharField(max_length=50)),
                (
                    "grammatical_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tag", models.CharField(blank=True, max_length=50, null=True)),
                ("word", models.BooleanField(blank=True)),
                ("sentence", models.BooleanField(blank=True)),
                ("date", models.DateField(auto_now=True, verbose_name="date added")),
            ],
            options={
                "verbose_name": "vocabulary",
                "verbose_name_plural": "vocabularies",
                "db_table": "user_glossary",
            },
        ),
        migrations.RemoveField(
            model_name="glossaryword",
            name="deck",
        ),
        migrations.RemoveField(
            model_name="glossaryword",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transsentence",
            name="sentence",
        ),
        migrations.RemoveField(
            model_name="transsentence",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transword",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transword",
            name="word",
        ),
        migrations.AlterModelOptions(
            name="userdeck",
            options={"verbose_name": "deck", "verbose_name_plural": "decks"},
        ),
        migrations.AlterField(
            model_name="userdeck",
            name="deck_name",
            field=models.CharField(max_length=100, verbose_name="deck name"),
        ),
        migrations.DeleteModel(
            name="GlossarySentence",
        ),
        migrations.DeleteModel(
            name="GlossaryWord",
        ),
        migrations.DeleteModel(
            name="TransSentence",
        ),
        migrations.DeleteModel(
            name="TransWord",
        ),
        migrations.AddField(
            model_name="userglossary",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.userdeck"
            ),
        ),
        migrations.AddField(
            model_name="userglossary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="transglossary",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.userdeck"
            ),
        ),
        migrations.AddField(
            model_name="transglossary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="transglossary",
            name="vocabulary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.userglossary"
            ),
        ),
    ]
