# Generated by Django 4.1.7 on 2023-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_userdeck_slug_alter_userglossary_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userglossary",
            name="sentence",
        ),
        migrations.RemoveField(
            model_name="userglossary",
            name="word",
        ),
        migrations.AddField(
            model_name="userglossary",
            name="category",
            field=models.CharField(default="", max_length=8),
        ),
    ]
