# Generated by Django 4.1.7 on 2023-05-12 03:46
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [CITextExtension()]
