# Generated by Django 4.1.7 on 2023-05-21 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_backup_email_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="user bio"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
