# Generated by Django 4.1.7 on 2023-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_options_alter_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="user_bio"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
